Repository team-faster/faster, pull requests merged in 2025-03, with the labels that each got.

#10 [setting] 초기 세팅
  .github/ISSUE_TEMPLATE/✨-oo기능-개발.md
  .github/ISSUE_TEMPLATE/🐛-oo에러-버그--수정.md
  .idea/git_toolbox_prj.xml
Labels: ✨ feature

#20 [order] 모듈 추가 및 단건 조회 기능 추가
  .gitignore
  order/build.gradle
  order/src/main/java/com/faster/order/OrderApplication.java
  order/src/main/java/com/faster/order/app/global/exception/OrderErrorCode.java
  order/src/main/java/com/faster/order/app/order/application/dto/response/OrderDetailApplicationResponseDto.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderService.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/faster/order/app/order/domain/entity/Order.java
  order/src/main/java/com/faster/order/app/order/domain/entity/OrderItem.java
  order/src/main/java/com/faster/order/app/order/domain/entity/OrderItems.java
  order/src/main/java/com/faster/order/app/order/domain/entity/OrdererInfo.java
  order/src/main/java/com/faster/order/app/order/domain/enums/OrderStatus.java
  order/src/main/java/com/faster/order/app/order/domain/repository/OrderRepository.java
  order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepository.java
  order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
  order/src/main/java/com/faster/order/app/order/presentation/dto/response/OrderDetailResponseDto.java
  order/src/main/resources/application.yml
  order/src/main/resources/db/data.sql
  order/src/main/resources/properties/base.yml
  order/src/main/resources/properties/cloud.yml
  order/src/main/resources/properties/datasource.yml
  order/src/main/resources/properties/jpa.yml
  settings.gradle
Labels: ✨ feature

#32 [hub] 허브 생성
  hub/build.gradle
  hub/src/main/java/com/faster/hub/HubApplication.java
  hub/src/main/java/com/faster/hub/app/hub/application/dto/CreateHubApplicationRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/dto/CreateHubResponseApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
  hub/src/main/java/com/faster/hub/app/hub/domain/entity/Hub.java
  hub/src/main/java/com/faster/hub/app/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/faster/hub/app/hub/infrastructure/persistence/HubJpaRepository.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubController.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/CreateHubRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/CreateHubResponseDto.java
  hub/src/main/resources/application.yml
  hub/src/main/resources/properties/base.yml
  hub/src/main/resources/properties/cloud.yml
  hub/src/main/resources/properties/datasource.yml
  hub/src/main/resources/properties/jpa.yml
  hub/src/test/hub.http
  settings.gradle
Labels: ✨ feature

#27 [order] 주문 삭제 기능 구현
  order/build.gradle
  order/src/main/java/com/faster/order/app/global/exception/OrderErrorCode.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderService.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/faster/order/app/order/domain/entity/Order.java
  order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
  order/src/main/resources/properties/base.yml
Labels: ✨ feature

#33 [common] 권한 체크 어노테이션 구현
  common/build.gradle
  common/src/main/java/com/common/aop/AuthCheckAspect.java
  common/src/main/java/com/common/aop/annotation/AuthCheck.java
Labels: ✨ feature

#45 [user] DDD 계층 구조에 따라서 도메인 설계하기
  message/src/main/resources/application.yml
  settings.gradle
  user/build.gradle
  user/src/main/java/com/faster/user/app/auth/application/dto/CreateUserRequestDto.java
  user/src/main/java/com/faster/user/app/auth/application/usecase/AuthService.java
  user/src/main/java/com/faster/user/app/auth/application/usecase/AuthUseCase.java
  user/src/main/java/com/faster/user/app/auth/config/SecurityConfig.java
  user/src/main/java/com/faster/user/app/auth/presentation/controller/AuthController.java
  user/src/main/java/com/faster/user/app/auth/presentation/dto/CreateUserResponseDto.java
  user/src/main/java/com/faster/user/app/global/exception/UserAlreadyExistsBySlackIdException.java
  user/src/main/java/com/faster/user/app/global/exception/UserAlreadyExistsByUsernameException.java
  user/src/main/java/com/faster/user/app/global/exception/enums/AuthErrorCode.java
  user/src/main/java/com/faster/user/app/global/exception/handler/AuthExceptionHandler.java
  user/src/main/java/com/faster/user/app/global/response/enums/UserResponseCode.java
  user/src/main/java/com/faster/user/app/user/domain/entity/User.java
  user/src/main/java/com/faster/user/app/user/domain/enums/Role.java
  user/src/main/java/com/faster/user/app/user/domain/repository/UserRepository.java
  user/src/main/resources/application.yml
Labels: ✨ feature

#44 [common] 페이지네이션 관련 공통 코드 추가
  common/src/main/java/com/common/config/WebConfig.java
  common/src/main/java/com/common/resolver/CustomPageableArgumentResolver.java
  common/src/main/java/com/common/response/PageResponse.java
Labels: ✨ feature

#47 [message] DDD 계층 구조에 따라서 도메인 설계하기
  message/build.gradle
  message/src/main/java/com/faster/message/app/global/MessageInvalidBySendAtException.java
  message/src/main/java/com/faster/message/app/global/MessageInvalidBySlackIdException.java
  message/src/main/java/com/faster/message/app/global/enums/MessageErrorCode.java
  message/src/main/java/com/faster/message/app/global/handler/MessageExceptionHandler.java
  message/src/main/java/com/faster/message/app/global/response/MessageResponseCode.java
  message/src/main/java/com/faster/message/app/message/application/dto/CreateMessageRequestDto.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageService.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageUseCase.java
  message/src/main/java/com/faster/message/app/message/domain/entity/Message.java
  message/src/main/java/com/faster/message/app/message/domain/enums/Type.java
  message/src/main/java/com/faster/message/app/message/domain/repository/MessageRepository.java
  message/src/main/java/com/faster/message/app/message/presentation/dto/response/CreateMessageResponseDto.java
  message/src/main/java/com/faster/message/app/message/presentation/internal/MessageInternalController.java
Labels: ✨ feature

#36 [hub] 단건 조회
  hub/src/main/java/com/faster/hub/app/global/exception/HubErrorCode.java
  hub/src/main/java/com/faster/hub/app/hub/application/dto/GetHubApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
  hub/src/main/java/com/faster/hub/app/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubController.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/GetHubResponseDto.java
  hub/src/test/hub.http
Labels: ✨ feature

#46 [user] DDD 계층 구조에 따라서 도메인 설계하기
  message/src/main/resources/application.yml
  settings.gradle
  user/build.gradle
  user/src/main/java/com/faster/user/app/auth/application/dto/CreateUserRequestDto.java
  user/src/main/java/com/faster/user/app/auth/application/usecase/AuthService.java
  user/src/main/java/com/faster/user/app/auth/application/usecase/AuthUseCase.java
  user/src/main/java/com/faster/user/app/auth/config/SecurityConfig.java
  user/src/main/java/com/faster/user/app/auth/presentation/controller/AuthController.java
  user/src/main/java/com/faster/user/app/auth/presentation/dto/CreateUserResponseDto.java
  user/src/main/java/com/faster/user/app/global/exception/UserAlreadyExistsBySlackIdException.java
  user/src/main/java/com/faster/user/app/global/exception/UserAlreadyExistsByUsernameException.java
  user/src/main/java/com/faster/user/app/global/exception/enums/AuthErrorCode.java
  user/src/main/java/com/faster/user/app/global/exception/handler/AuthExceptionHandler.java
  user/src/main/java/com/faster/user/app/global/response/enums/UserResponseCode.java
  user/src/main/java/com/faster/user/app/user/domain/entity/User.java
  user/src/main/java/com/faster/user/app/user/domain/enums/Role.java
  user/src/main/java/com/faster/user/app/user/domain/repository/UserRepository.java
  user/src/main/resources/application.yml
Labels: ✨ feature

#49 [hub] 단건 수정
  hub/src/main/java/com/faster/hub/app/hub/application/dto/UpdateHubApplicationRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/dto/UpdateHubApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
  hub/src/main/java/com/faster/hub/app/hub/domain/entity/Hub.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubController.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/UpdateHubRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/UpdateHubResponseDto.java
  hub/src/test/hub.http
Labels: ✨ feature

#51 [hub] 단건 삭제
  hub/src/main/java/com/faster/hub/app/hub/application/dto/DeleteHubApplicationRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubController.java
  hub/src/test/hub.http
Labels: ✨ feature

#56 [common] 공통 코드 의존성, 글로벌익셉션 핸들러 추가
  common/build.gradle
  common/src/main/java/com/common/exception/GlobalErrorHandler.java
Labels: ✨ feature

#54 [common] 페이지응답 레코드에 map() 메소드 추가
  common/src/main/java/com/common/response/PageResponse.java
Labels: ✨ feature

#57 [hub] api refactor - 클래스명 변경, 권한 변경
  hub/src/main/java/com/faster/hub/app/hub/application/dto/SaveHubApplicationRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/dto/SaveHubApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubController.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/SaveHubRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/SaveHubResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/UpdateHubRequestDto.java
Labels: ♻️ refactor

#50 [delivery] 배달 생성 기능 추가
  common/src/main/java/com/common/domain/BaseEntity.java
  delivery/build.gradle
  delivery/src/main/java/com/faster/delivery/DeliveryApplication.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/application/dto/DeliverySaveDto.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/application/usecase/DeliveryService.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/domain/entity/DeliveryRoute.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/feign/CompanyClient.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/feign/HubClient.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/feign/dto/company/CompanyGetResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/feign/dto/hub/HubPathRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/feign/dto/hub/HubPathResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/jpa/DeliveryJpaRepository.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/jpa/DeliveryRepositoryCustom.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/infrastructure/jpa/DeliveryRepositoryCustomImpl.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/presentaion/DeliveryApiController.java
  delivery/src/main/java/com/faster/delivery/app/domains/delivery/presentaion/dto/DeliverySaveRequestDto.java
  delivery/src/main/resources/application-develop.yml
  delivery/src/main/resources/application-test.yml
  delivery/src/main/resources/application.yml
  delivery/src/test/java/com/faster/delivery/DeliveryApplicationTests.java
  delivery/src/test/java/com/faster/delivery/app/domains/delivery/application/usecase/DeliveryServiceTest.java
Labels: ✨ feature

#60 [common] AuthCheck NullpointerException 해결
  common/src/main/java/com/common/aop/AuthCheckAspect.java
Labels: 🐛 bug

#58 [order] 주문 검색 조회
  order/build.gradle
  order/src/main/java/com/faster/order/app/global/config/QuerydslConfig.java
  order/src/main/java/com/faster/order/app/global/exception/OrderErrorCode.java
  order/src/main/java/com/faster/order/app/global/utils/QuerydslUtil.java
  order/src/main/java/com/faster/order/app/order/application/dto/request/SearchOrderConditionDto.java
  order/src/main/java/com/faster/order/app/order/application/dto/response/SearchOrderApplicationResponseDto.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderService.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/faster/order/app/order/domain/entity/OrderItem.java
  order/src/main/java/com/faster/order/app/order/domain/repository/OrderRepository.java
  order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepository.java
  order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepositoryCustom.java
  order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepositoryCustomImpl.java
  order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/dto/response/OrderQuerydslResponseDto.java
  order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
  order/src/main/java/com/faster/order/app/order/presentation/dto/response/SearchOrderResponseDto.java
  order/src/main/resources/properties/base.yml
  order/src/main/resources/properties/cloud.yml
  order/src/main/resources/properties/datasource.yml
  order/src/main/resources/properties/jpa.yml
  order/src/test/java/com/faster/order/app/order/application/usecase/OrderServiceTest.java
  order/src/test/java/com/faster/order/app/order/fixture/OrderFixture.java
  order/src/test/java/com/faster/order/app/order/utils/DatabaseCleanUp.java
  order/src/test/order.http
Labels: ✨ feature

#61 [order] 단건 조회, 삭제 refactor
  order/src/main/java/com/faster/order/app/order/application/dto/response/GetOrderDetailApplicationResponseDto.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderService.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
  order/src/main/java/com/faster/order/app/order/presentation/dto/response/GetOrderDetailResponseDto.java
Labels: ♻️ refactor

#69 [message] DDD 계층 구조에 따라서 도메인 설계하기
  message/src/main/java/com/faster/message/app/global/MessageInvalidBySendAtException.java
  message/src/main/java/com/faster/message/app/global/MessageInvalidBySlackIdException.java
  message/src/main/java/com/faster/message/app/global/handler/MessageExceptionHandler.java
  message/src/main/java/com/faster/message/app/global/response/MessageResponseCode.java
  message/src/main/java/com/faster/message/app/message/application/dto/CreateGeminiMessageRequestDto.java
  message/src/main/java/com/faster/message/app/message/application/dto/CreateMessageRequestDto.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageService.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageServiceImpl.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageUseCase.java
  message/src/main/java/com/faster/message/app/message/domain/entity/Message.java
  message/src/main/java/com/faster/message/app/message/domain/enums/MessageType.java
  message/src/main/java/com/faster/message/app/message/presentation/dto/response/CreateMessageResponseDto.java
  message/src/main/java/com/faster/message/app/message/presentation/internal/MessageInternalController.java
Labels: ✨ feature

#68 [order] 주문 취소 기능 구현
  order/src/main/java/com/faster/order/app/global/exception/OrderErrorCode.java
  order/src/main/java/com/faster/order/app/order/application/dto/response/CancelOrderApplicationResponseDto.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderService.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/faster/order/app/order/domain/entity/Order.java
  order/src/main/java/com/faster/order/app/order/domain/repository/OrderRepository.java
  order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
  order/src/main/java/com/faster/order/app/order/presentation/dto/response/CancelOrderResponseDto.java
  order/src/test/order.http
Labels: ✨ feature

#71 [order] 내부 주문 확정 기능 구현
  order/src/main/java/com/faster/order/app/order/application/dto/response/InternalConfirmOrderApplicationResponseDto.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderService.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/faster/order/app/order/domain/entity/Order.java
  order/src/main/java/com/faster/order/app/order/presentation/OrderInternalController.java
  order/src/main/java/com/faster/order/app/order/presentation/dto/response/InternalConfirmOrderResponseDto.java
  order/src/test/order.http
Labels: ✨ feature

#73 [order] 주문 상태 변경 기능 구현
  order/src/main/java/com/faster/order/app/global/config/FeignClientConfig.java
  order/src/main/java/com/faster/order/app/global/exception/OrderErrorCode.java
  order/src/main/java/com/faster/order/app/order/application/ProductClient.java
  order/src/main/java/com/faster/order/app/order/application/dto/request/SearchOrderConditionDto.java
  order/src/main/java/com/faster/order/app/order/application/dto/response/InternalUpdateOrderStatusApplicationResponseDto.java
  order/src/main/java/com/faster/order/app/order/application/dto/response/SearchOrderApplicationResponseDto.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderService.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/faster/order/app/order/domain/criteria/SearchOrderCriteria.java
  order/src/main/java/com/faster/order/app/order/domain/entity/Order.java
  order/src/main/java/com/faster/order/app/order/domain/enums/OrderStatus.java
  order/src/main/java/com/faster/order/app/order/domain/projection/SearchOrderProjection.java
  order/src/main/java/com/faster/order/app/order/domain/repository/OrderRepository.java
  order/src/main/java/com/faster/order/app/order/infrastructure/ProductClientImpl.java
  order/src/main/java/com/faster/order/app/order/infrastructure/feign/ProductFeignClient.java
  order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepositoryCustom.java
  order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepositoryCustomImpl.java
  order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
  order/src/main/java/com/faster/order/app/order/presentation/OrderInternalController.java
  order/src/main/java/com/faster/order/app/order/presentation/dto/request/InternalUpdateOrderStatusRequestDto.java
  order/src/main/java/com/faster/order/app/order/presentation/dto/response/InternalUpdateOrderStatusResponseDto.java
  order/src/test/order.http
Labels: ✨ feature

#79 [message] 코드 컨벤션 규칙에 따라 수정 및 코드 분할
  message/src/main/java/com/faster/message/app/message/application/dto/SaveGeminiMessageRequestDto.java
  message/src/main/java/com/faster/message/app/message/application/dto/SaveMessageRequestDto.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageService.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageServiceImpl.java
  message/src/main/java/com/faster/message/app/message/presentation/dto/response/SaveMessageResponseDto.java
  message/src/main/java/com/faster/message/app/message/presentation/internal/MessageInternalController.java
Labels: ♻️ refactor, ✏️ fix typos

#48 [message] DDD 계층 구조에 따라서 도메인 설계하기
  message/build.gradle
  message/src/main/java/com/faster/message/app/global/enums/MessageErrorCode.java
  message/src/main/java/com/faster/message/app/global/response/MessageResponseCode.java
  message/src/main/java/com/faster/message/app/message/application/dto/SaveGeminiMessageRequestDto.java
  message/src/main/java/com/faster/message/app/message/application/dto/SaveMessageRequestDto.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageService.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageServiceImpl.java
  message/src/main/java/com/faster/message/app/message/domain/entity/Message.java
  message/src/main/java/com/faster/message/app/message/domain/enums/MessageType.java
  message/src/main/java/com/faster/message/app/message/domain/repository/MessageRepository.java
  message/src/main/java/com/faster/message/app/message/presentation/dto/response/SaveMessageResponseDto.java
  message/src/main/java/com/faster/message/app/message/presentation/internal/MessageInternalController.java
Labels: ✨ feature

#80 [order] 주문 생성 기능 구현
  order/src/main/java/com/faster/order/app/order/application/dto/request/SaveOrderApplicationRequestDto.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderService.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/faster/order/app/order/domain/entity/Order.java
  order/src/main/java/com/faster/order/app/order/domain/entity/OrderItem.java
  order/src/main/java/com/faster/order/app/order/domain/entity/OrderItems.java
  order/src/main/java/com/faster/order/app/order/domain/entity/OrdererInfo.java
  order/src/main/java/com/faster/order/app/order/domain/repository/OrderRepository.java
  order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
  order/src/main/java/com/faster/order/app/order/presentation/dto/request/SaveOrderRequestDto.java
  order/src/test/java/com/faster/order/app/order/fixture/OrderFixture.java
  order/src/test/order.http
Labels: ✨ feature

#83 [product] 상품 모듈 생성
  product/build.gradle
  product/src/main/java/com/faster/product/ProductApplication.java
  product/src/main/java/com/faster/product/app/global/config/FeignClientConfig.java
  product/src/main/java/com/faster/product/app/global/config/QuerydslConfig.java
  product/src/main/java/com/faster/product/app/global/utils/QuerydslUtil.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/domain/entity/Product.java
  product/src/main/java/com/faster/product/app/product/domain/repository/ProductRepository.java
  product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepository.java
  product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepositoryCustom.java
  product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepositoryCustomImpl.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/ProductController.java
  product/src/main/resources/application.yml
  product/src/main/resources/db/data.sql
  product/src/main/resources/properties/base.yml
  product/src/main/resources/properties/cloud.yml
  product/src/main/resources/properties/datasource.yml
  product/src/main/resources/properties/jpa.yml
  settings.gradle
Labels: ✨ feature

#87 [product] 상품 단건 조회 구현
  product/src/main/java/com/faster/product/app/global/exception/ProductErrorCode.java
  product/src/main/java/com/faster/product/app/product/application/dto/GetProductDetailApplicationResponseDto.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/domain/entity/Product.java
  product/src/main/java/com/faster/product/app/product/domain/repository/ProductRepository.java
  product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepository.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/ProductController.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/ProductInternalController.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/response/GetProductDetailResponseDto.java
  product/src/main/resources/db/data.sql
  product/src/main/resources/properties/datasource.yml
  product/src/test/product.http
Labels: ✨ feature

#89 [product] 상품 단건 삭제 구현
  product/src/main/java/com/faster/product/app/global/exception/ProductErrorCode.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/ProductController.java
  product/src/test/product.http
Labels: ✨ feature

#95 [product] 상품 조회/삭제 리팩토링
  product/src/main/java/com/faster/product/app/product/application/dto/response/GetProductDetailApplicationResponseDto.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/response/GetProductDetailResponseDto.java
Labels: ♻️ refactor

#96 [product] 상품 생성 기능 구현
  product/src/main/java/com/faster/product/app/product/application/dto/request/SaveProductApplicationRequestDto.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/domain/entity/Product.java
  product/src/main/java/com/faster/product/app/product/presentation/ProductController.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/request/SaveProductRequestDto.java
  product/src/test/product.http
Labels: ✨ feature

#100 [product] 내부 상품 목록 조회
  product/src/main/java/com/faster/product/app/product/application/usecase/GetProductsApplicationResponseDto.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/domain/repository/ProductRepository.java
  product/src/main/java/com/faster/product/app/product/presentation/ProductInternalController.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/response/GetProductsResponseDto.java
  product/src/test/product.http
Labels: ✨ feature

#101 [user] 설정파일 변경
  user/src/main/resources/application.yml
  user/src/main/resources/properties/base.yml
  user/src/main/resources/properties/cloud.yml
  user/src/main/resources/properties/datasource.yml
  user/src/main/resources/properties/jpa.yml
  user/src/main/resources/properties/jwt.yml
Labels: ♻️ refactor

#97 [gateway] 인증/인가 구현
  gateway/build.gradle
  gateway/src/main/java/com/faster/gateway/app/global/config/SecurityConfig.java
  gateway/src/main/java/com/faster/gateway/app/global/config/WebFluxConfig.java
  gateway/src/main/java/com/faster/gateway/app/global/exception/GatewayErrorCode.java
  gateway/src/main/java/com/faster/gateway/app/global/filter/UserInfoFilter.java
  gateway/src/main/java/com/faster/gateway/app/global/security/handler/ExceptionHandlingFilter.java
  gateway/src/main/java/com/faster/gateway/app/global/security/jwt/filter/JwtAuthenticationFilter.java
  gateway/src/main/java/com/faster/gateway/app/global/security/jwt/util/TokenProvider.java
  gateway/src/main/java/com/faster/gateway/app/global/security/service/CustomUserDetailsService.java
  gateway/src/main/java/com/faster/gateway/app/global/security/service/dto/Authenticated.java
  gateway/src/main/java/com/faster/gateway/app/global/security/service/dto/CustomUserDetails.java
  gateway/src/main/java/com/faster/gateway/app/global/security/service/dto/UserDetailsDto.java
  gateway/src/main/java/com/faster/gateway/app/user/domain/entity/User.java
  gateway/src/main/java/com/faster/gateway/app/user/domain/repository/UserJpaRepository.java
  gateway/src/main/java/com/faster/gateway/app/user/infrastructure/UserRepository.java
  gateway/src/main/resources/application.yml
  gateway/src/main/resources/properties/base.yml
  gateway/src/main/resources/properties/cloud.yml
  gateway/src/main/resources/properties/datasource.yml
  gateway/src/main/resources/properties/gateway-route.yml
  gateway/src/main/resources/properties/jpa.yml
  gateway/src/main/resources/properties/jwt.yml
Labels: ✨ feature

#103 [product] 내부 상품 재고 수정 기능 구현
  product/src/main/java/com/faster/product/app/global/exception/ProductErrorCode.java
  product/src/main/java/com/faster/product/app/product/application/dto/request/UpdateStocksApplicationRequestDto.java
  product/src/main/java/com/faster/product/app/product/application/dto/response/UpdateStocksApplicationResponseDto.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/domain/entity/Product.java
  product/src/main/java/com/faster/product/app/product/presentation/ProductInternalController.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/request/UpdateStocksRequestDto.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/response/UpdateStocksResponseDto.java
  product/src/test/product.http
Labels: ✨ feature

#92 [user] feat: 회원 소프트 삭제
  user/src/main/java/com/faster/user/app/auth/application/usecase/AuthServiceImpl.java
  user/src/main/java/com/faster/user/app/global/response/enums/UserResponseCode.java
  user/src/main/java/com/faster/user/app/user/application/dto/DeleteUserRequestDto.java
  user/src/main/java/com/faster/user/app/user/application/usecase/UserService.java
  user/src/main/java/com/faster/user/app/user/application/usecase/UserServiceImpl.java
  user/src/main/java/com/faster/user/app/user/domain/entity/User.java
  user/src/main/java/com/faster/user/app/user/infrastructure/persistence/jpa/UserJpaRepository.java
  user/src/main/java/com/faster/user/app/user/infrastructure/persistence/jpa/UserRepositoryAdapter.java
  user/src/main/java/com/faster/user/app/user/presentation/controller/UserController.java
  user/src/main/java/com/faster/user/app/user/presentation/dto/DeleteUserResponseDto.java
  user/src/main/java/com/faster/user/app/user/presentation/internal/InternalUserController.java
Labels: ✨ feature

#110 [auth] 액세스 토큰 안에 회원 ID ,권한 포함
  user/src/main/java/com/faster/user/app/auth/application/usecase/AuthServiceImpl.java
  user/src/main/java/com/faster/user/app/auth/jwt/JwtProvider.java
Labels: ✨ feature

#111 [company] 업체 프로젝트 생성 및 엔티티, 리포지토리 생성하기
  company/build.gradle
  company/src/main/java/com/faster/company/CompanyApplication.java
  company/src/main/java/com/faster/company/app/company/application/usecase/CompanyService.java
  company/src/main/java/com/faster/company/app/company/application/usecase/CompanyServiceImpl.java
  company/src/main/java/com/faster/company/app/company/domain/entity/Company.java
  company/src/main/java/com/faster/company/app/company/domain/enums/CompanyType.java
  company/src/main/java/com/faster/company/app/company/domain/repository/CompanyRepository.java
  company/src/main/java/com/faster/company/app/company/infrastructure/persistence/jpa/CompanyJpaRepository.java
  company/src/main/java/com/faster/company/app/company/presentation/CompanyController.java
  company/src/main/java/com/faster/company/app/company/presentation/dto/SaveCompanyResponseDto.java
  settings.gradle
  user/src/main/java/com/faster/user/app/auth/application/dto/SaveUserRequestDto.java
  user/src/main/java/com/faster/user/app/auth/presentation/dto/SaveUserResponseDto.java
Labels: ✨ feature

#109 [delivery] feat: 배송 상세 조회 기능 추가 (임시)
  delivery/build.gradle
  delivery/src/main/java/com/faster/delivery/app/delivery/application/CompanyClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/DeliveryManagerClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/HubClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/CompanyDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/DeliveryDetailDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/DeliveryManagerDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/HubRouteDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/CompanyClientImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/CompanyFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/DeliveryManagerFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/DeliveryManagerImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/HubClientImplForDelivery.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/HubFeginClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/company/CompanyGetResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/deliverymanager/DeliveryManagerGetResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/hub/HubPathRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/hub/HubPathResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/feign/dto/hub/HubPathResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/jpa/DeliveryJpaRepository.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/jpa/DeliveryRepositoryCustom.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/jpa/DeliveryRepositoryCustomImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryApiController.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/dto/HubDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/dto/UserDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/entity/DeliveryManager.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/HubClientImplForDeliveryManager.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/HubFeginClient.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/UserClientImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/dto/HubGetResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/dto/UserGetResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/global/config/QuerydslConfig.java
  delivery/src/test/java/com/faster/delivery/app/domains/delivery/application/usecase/DeliveryServiceTest.java
Labels: ✨ feature

#117 [product] 상품 코드 feign 설정 추가 및 리팩토링
  product/build.gradle
  product/src/main/java/com/faster/product/app/global/config/FeignClientConfig.java
  product/src/main/java/com/faster/product/app/product/application/dto/request/GetProductsApplicationResponseDto.java
  product/src/main/java/com/faster/product/app/product/application/dto/request/UpdateStocksApplicationRequestDto.java
  product/src/main/java/com/faster/product/app/product/application/dto/response/UpdateStocksApplicationResponseDto.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/presentation/ProductInternalController.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/response/GetProductsResponseDto.java
  product/src/main/resources/db/data.sql
  product/src/test/product.http
Labels: ♻️ refactor

#124 [hub] hub route search
  hub/src/main/java/com/faster/hub/app/global/exception/HubErrorCode.java
  hub/src/main/java/com/faster/hub/app/hub/application/dto/request/DeleteHubApplicationRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/dto/request/GetPathApplicationRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/dto/request/SaveHubApplicationRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/dto/request/UpdateHubApplicationRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/dto/response/GetHubApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/dto/response/GetPathsApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/dto/response/SaveHubApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/dto/response/UpdateHubApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/DijkstraPathFinder.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/PathFinder.java
  hub/src/main/java/com/faster/hub/app/hub/domain/entity/Hub.java
  hub/src/main/java/com/faster/hub/app/hub/domain/entity/HubRoute.java
  hub/src/main/java/com/faster/hub/app/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubController.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubInternalController.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/request/SaveHubRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/request/UpdateHubRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/response/GetHubResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/response/GetPathsResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/response/SaveHubResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/response/UpdateHubResponseDto.java
  hub/src/test/hub.http
Labels: ✨ feature

#123 [product] 업체 서비스 클라이언트 연동
  product/src/main/java/com/faster/product/app/global/exception/ProductErrorCode.java
  product/src/main/java/com/faster/product/app/product/application/CompanyClient.java
  product/src/main/java/com/faster/product/app/product/application/dto/request/UpdateStocksApplicationRequestDto.java
  product/src/main/java/com/faster/product/app/product/application/dto/response/GetCompanyApplicationResponseDto.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/domain/entity/Product.java
  product/src/main/java/com/faster/product/app/product/infrastructure/CompanyClientImpl.java
  product/src/main/java/com/faster/product/app/product/infrastructure/feign/CompanyFeignClient.java
  product/src/main/java/com/faster/product/app/product/infrastructure/feign/dto/response/GetCompanyResponseDto.java
  product/src/main/java/com/faster/product/app/product/presentation/ProductController.java
Labels: ✨ feature

#126 [delivery] feat: 배송 상태 업데이트 기능 구현
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/DeliveryUpdateDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryService.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryApiController.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/DeliveryUpdateRequestDto.java
Labels: ✨ feature

#129 [deliveryManager] feat: 배송담당자 상세조회,수정,삭제 기능 추가
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/hub/HubPathResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/dto/DeliveryManagerDetailDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/dto/DeliveryManagerUpdateDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerService.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/entity/DeliveryManager.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/repository/DeliveryManagerRepository.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/DeliveryManagerApiController.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/dto/DeliveryManagerGetDetailResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/dto/DeliveryManagerUpdateRequestDto.java
Labels: ✨ feature

#130 [delivery] feat: 배송 삭제 기능 구현
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryService.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryApiController.java
Labels: ✨ feature

#131 [product] 상품 목록 검색 기능 구현
  product/src/main/java/com/faster/product/app/global/exception/ProductErrorCode.java
  product/src/main/java/com/faster/product/app/product/application/dto/request/GetProductsApplicationResponseDto.java
  product/src/main/java/com/faster/product/app/product/application/dto/request/SearchProductConditionDto.java
  product/src/main/java/com/faster/product/app/product/application/dto/response/SearchProductApplicationResponseDto.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/domain/criteria/SearchProductCriteria.java
  product/src/main/java/com/faster/product/app/product/domain/repository/ProductRepository.java
  product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepositoryCustom.java
  product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepositoryCustomImpl.java
  product/src/main/java/com/faster/product/app/product/presentation/ProductController.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/response/GetProductsResponseDto.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/response/SearchProductResponseDto.java
  product/src/test/product.http
Labels: ✨ feature

#133 [hub] 허브 담당자 컬럼 추가 및 리스트 내부 조회
  hub/src/main/java/com/faster/hub/app/hub/application/dto/response/GetHubsApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
  hub/src/main/java/com/faster/hub/app/hub/domain/entity/Hub.java
  hub/src/main/java/com/faster/hub/app/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/GetHubsResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubInternalController.java
  hub/src/test/hub.http
Labels: ✨ feature

#135 [hub] 리펙토링
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/DijkstraPathFinder.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/PathFinder.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/request/DeleteHubApplicationRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/request/GetPathApplicationRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/request/SaveHubApplicationRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/request/UpdateHubApplicationRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/response/GetHubApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/response/GetHubsApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/response/GetPathsApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/response/SaveHubApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/response/UpdateHubApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubController.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubInternalController.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/request/SaveHubRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/request/UpdateHubRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/response/GetHubResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/response/GetHubsResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/response/GetPathsResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/response/SaveHubResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/response/UpdateHubResponseDto.java
  hub/src/test/hub.http
Labels: ♻️ refactor

#136 [product] 상품 재고 차감시 비관적 락 적용
  order/src/main/java/com/faster/order/app/order/infrastructure/ProductClientImpl.java
  product/src/main/java/com/faster/product/app/product/application/dto/request/SortedUpdateStocksApplicationRequestDto.java
  product/src/main/java/com/faster/product/app/product/application/dto/request/UpdateStocksApplicationRequestDto.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/domain/repository/ProductRepository.java
  product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepository.java
  product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepositoryCustomImpl.java
  product/src/main/java/com/faster/product/app/product/presentation/ProductInternalController.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/request/UpdateStocksRequestDto.java
  product/src/test/java/com/faster/product/app/product/application/usecase/ProductServiceImplTest.java
  product/src/test/java/com/faster/product/app/product/fixture/ProductFixture.java
  product/src/test/java/utils/DatabaseCleanUp.java
Labels: ♻️ refactor

#138 [delivery] feat: internal api 기본 구성 추가
  delivery/build.gradle
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/CompanyDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryService.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/CompanyFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/DeliveryManagerFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/HubFeginClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/company/CompanyGetResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryApiController.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryInternalController.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/api/DeliverySaveRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/api/DeliveryUpdateRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/internal/DeliverySaveInternalRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/internal/DeliveryUpdateInternalRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/HubFeginClient.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/UserFeginClient.java
  delivery/src/main/java/com/faster/delivery/app/global/config/FeignClientConfig.java
Labels: ✨ feature

#139 [order] 배송 서비스 클라이언트 연동
  order/src/main/java/com/faster/order/app/order/application/client/CompanyClient.java
  order/src/main/java/com/faster/order/app/order/application/client/DeliveryClient.java
  order/src/main/java/com/faster/order/app/order/application/client/ProductClient.java
  order/src/main/java/com/faster/order/app/order/application/dto/request/SaveDeliveryApplicationRequestDto.java
  order/src/main/java/com/faster/order/app/order/application/dto/response/CancelDeliveryApplicationResponseDto.java
  order/src/main/java/com/faster/order/app/order/application/dto/response/SaveDeliveryApplicationResponseDto.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/faster/order/app/order/domain/entity/Order.java
  order/src/main/java/com/faster/order/app/order/domain/repository/OrderRepository.java
  order/src/main/java/com/faster/order/app/order/infrastructure/CompanyClientImpl.java
  order/src/main/java/com/faster/order/app/order/infrastructure/DeliveryClientImpl.java
  order/src/main/java/com/faster/order/app/order/infrastructure/ProductClientImpl.java
  order/src/main/java/com/faster/order/app/order/infrastructure/feign/DeliveryFeignClient.java
  order/src/main/java/com/faster/order/app/order/infrastructure/feign/dto/request/CancelDeliveryRequestDto.java
  order/src/main/java/com/faster/order/app/order/infrastructure/feign/dto/request/SaveDeliveryRequestDto.java
  order/src/main/java/com/faster/order/app/order/infrastructure/feign/dto/response/CancelDeliveryResponseDto.java
  order/src/main/java/com/faster/order/app/order/infrastructure/feign/dto/response/SaveDeliveryResponseDto.java
  order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepository.java
  order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepositoryCustomImpl.java
  order/src/main/resources/db/data.sql
Labels: ✨ feature

#148 [common] feignClient 에러디코더 추가에 따른 공통 예외 수정
  common/src/main/java/com/common/exception/CustomException.java
  common/src/main/java/com/common/exception/GlobalErrorHandler.java
  gateway/src/main/java/com/faster/gateway/app/global/security/handler/ExceptionHandlingFilter.java
  order/src/main/java/com/faster/order/app/global/feign/FeignClientErrorDecoder.java
Labels: ♻️ refactor

#149 [hub] hub-route update
  hub/src/main/java/com/faster/hub/app/global/config/DirectionsApiClientConfig.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/DirectionsApiClient.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/response/DirectionsApiApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/response/UpdateHubRoutesApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/domain/entity/HubRoute.java
  hub/src/main/java/com/faster/hub/app/hub/infrastructure/client/NaverDirectionsApiClientImpl.java
  hub/src/main/java/com/faster/hub/app/hub/infrastructure/client/feign/NaverDirectionsApiFeignClient.java
  hub/src/main/java/com/faster/hub/app/hub/infrastructure/client/feign/dto/NaverDirectionsApiFeignClientResponse.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubController.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/response/UpdateHubRoutesResponseDto.java
  hub/src/main/resources/application.yml
  hub/src/main/resources/properties/directions-api.yml
  hub/src/test/hub.http
Labels: ✨ feature

#145 [user] 로그아웃과 재발급 구현
  user/build.gradle
  user/src/main/java/com/faster/user/app/auth/application/usecase/AuthService.java
  user/src/main/java/com/faster/user/app/auth/application/usecase/AuthServiceImpl.java
  user/src/main/java/com/faster/user/app/auth/config/RedisConfig.java
  user/src/main/java/com/faster/user/app/auth/jwt/JwtProvider.java
  user/src/main/java/com/faster/user/app/auth/presentation/controller/AuthController.java
  user/src/main/java/com/faster/user/app/auth/presentation/dto/requset/GenerateNewRefreshTokenRequestDto.java
  user/src/main/java/com/faster/user/app/auth/presentation/dto/requset/LogoutUserRequestDto.java
  user/src/main/java/com/faster/user/app/auth/presentation/dto/response/SaveUserResponseDto.java
  user/src/main/java/com/faster/user/app/auth/presentation/dto/response/SignInUserResponseDto.java
  user/src/main/java/com/faster/user/app/global/exception/enums/AuthErrorCode.java
  user/src/main/java/com/faster/user/app/user/presentation/InternalUserController.java
  user/src/main/java/com/faster/user/app/user/presentation/UserController.java
Labels: ✨ feature

#156 [delivery, deliveryManager] internal api 생성, 권한 로직 생성, 외부 요청 로직 구현
  delivery/src/main/java/com/faster/delivery/app/delivery/application/HubClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/OrderClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/DeliveryDetailDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/DeliveryGetElementDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryService.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/HubClientImplForDelivery.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/HubFeginClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/OrderClientImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/OrderFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/hub/HubPathResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/jpa/DeliveryRepositoryCustom.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/jpa/DeliveryRepositoryCustomImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryApiController.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/api/DeliveryGetDetailResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/internal/OrderUpdateRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/internal/OrderUpdateResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/HubClient.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/dto/HubDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerService.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/HubClientImplForDeliveryManager.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/HubFeginClient.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/dto/HubGetListResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/DeliveryManagerApiController.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/DeliveryManagerInternalController.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/dto/api/DeliveryManagerGetDetailResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/dto/api/DeliveryManagerSaveRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/dto/api/DeliveryManagerUpdateRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/dto/internal/DeliveryManagerGetDetailResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/global/common/CommonUtil.java
  delivery/src/main/java/com/faster/delivery/app/global/common/QueryDslUtil.java
  delivery/src/main/java/com/faster/delivery/app/global/config/FeignClientConfig.java
Labels: ✨ feature

#153 [company] 업체 단건 조회 기능 구현
  company/src/main/java/com/faster/company/app/company/application/dto/response/GetCompanyApplicationResponseDto.java
  company/src/main/java/com/faster/company/app/company/application/usecase/CompanyService.java
  company/src/main/java/com/faster/company/app/company/application/usecase/CompanyServiceImpl.java
  company/src/main/java/com/faster/company/app/company/presentation/CompanyController.java
  company/src/main/java/com/faster/company/app/company/presentation/dto/response/GetCompanyResponseDto.java
  company/src/test/company.http
Labels: ✨ feature

#157 [hub] search
  hub/build.gradle
  hub/src/main/java/com/faster/hub/app/global/config/QuerydslConfig.java
  hub/src/main/java/com/faster/hub/app/global/exception/HubErrorCode.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/request/GetHubsApplicationRequestDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/request/SearchHubCondition.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/response/GetHubsApplicationInternalResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/dto/response/GetHubsApplicationResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/domain/projection/SearchHubProjection.java
  hub/src/main/java/com/faster/hub/app/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/faster/hub/app/hub/infrastructure/persistence/HubJpaRepository.java
  hub/src/main/java/com/faster/hub/app/hub/infrastructure/persistence/HubJpaRepositoryCustom.java
  hub/src/main/java/com/faster/hub/app/hub/infrastructure/persistence/HubJpaRepositoryCustomImpl.java
  hub/src/main/java/com/faster/hub/app/hub/infrastructure/persistence/command/SearchHubsByConditionCommand.java
  hub/src/main/java/com/faster/hub/app/hub/infrastructure/persistence/util/QuerydslUtil.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubController.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubInternalController.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/response/GetHubsInternalResponseDto.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/dto/response/GetHubsResponseDto.java
  hub/src/test/hub.http
Labels: ✨ feature

#158 [company] 업체 수정 기능 구현
  company/src/main/java/com/faster/company/app/company/application/client/ProductClient.java
  company/src/main/java/com/faster/company/app/company/application/dto/request/UpdateCompanyApplicationRequestDto.java
  company/src/main/java/com/faster/company/app/company/application/dto/request/UpdateProductHubApplicationRequestDto.java
  company/src/main/java/com/faster/company/app/company/application/dto/response/UpdateCompanyApplicationResponseDto.java
  company/src/main/java/com/faster/company/app/company/application/dto/response/UpdateProductHubApplicationResponseDto.java
  company/src/main/java/com/faster/company/app/company/application/usecase/CompanyService.java
  company/src/main/java/com/faster/company/app/company/application/usecase/CompanyServiceImpl.java
  company/src/main/java/com/faster/company/app/company/domain/command/UpdateCompanyCommand.java
  company/src/main/java/com/faster/company/app/company/domain/entity/Company.java
  company/src/main/java/com/faster/company/app/company/infrastructure/HubClientImpl.java
  company/src/main/java/com/faster/company/app/company/infrastructure/ProductClientImpl.java
  company/src/main/java/com/faster/company/app/company/infrastructure/feign/ProductFeignClient.java
  company/src/main/java/com/faster/company/app/company/infrastructure/feign/dto/request/UpdateProductHubRequestDto.java
  company/src/main/java/com/faster/company/app/company/infrastructure/feign/dto/response/UpdateProductHubResponseDto.java
  company/src/main/java/com/faster/company/app/company/presentation/CompanyController.java
  company/src/main/java/com/faster/company/app/company/presentation/dto/request/UpdateCompanyRequestDto.java
  company/src/main/java/com/faster/company/app/company/presentation/dto/response/UpdateCompanyResponseDto.java
  company/src/main/java/com/faster/company/app/global/exception/CompanyErrorCode.java
  company/src/test/company.http
Labels: ✨ feature

#162 [company] 업체 단건 삭제 기능 구현
  company/src/main/java/com/faster/company/app/company/application/client/ProductClient.java
  company/src/main/java/com/faster/company/app/company/application/usecase/CompanyService.java
  company/src/main/java/com/faster/company/app/company/application/usecase/CompanyServiceImpl.java
  company/src/main/java/com/faster/company/app/company/domain/entity/Company.java
  company/src/main/java/com/faster/company/app/company/infrastructure/ProductClientImpl.java
  company/src/main/java/com/faster/company/app/company/infrastructure/feign/ProductFeignClient.java
  company/src/main/java/com/faster/company/app/company/presentation/CompanyController.java
  company/src/main/java/com/faster/company/app/company/presentation/dto/response/UpdateCompanyResponseDto.java
  company/src/test/company.http
Labels: ✨ feature

#165 [product] 상품 허브 업데이트 내부 api 구현
  product/src/main/java/com/faster/product/app/product/application/dto/request/UpdateProductHubApplicationRequestDto.java
  product/src/main/java/com/faster/product/app/product/application/dto/response/UpdateProductHubApplicationResponseDto.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/domain/repository/ProductRepository.java
  product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepository.java
  product/src/main/java/com/faster/product/app/product/presentation/ProductInternalController.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/request/UpdateProductHubRequestDto.java
  product/src/main/java/com/faster/product/app/product/presentation/dto/response/UpdateProductHubResponseDto.java
  product/src/test/java/com/faster/product/app/product/application/usecase/ProductServiceTest.java
  product/src/test/product.http
Labels: ✨ feature

#168 [product] 업체별 상품 삭제 내부 api 구현
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductService.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/domain/repository/ProductRepository.java
  product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepository.java
  product/src/main/java/com/faster/product/app/product/presentation/ProductInternalController.java
  product/src/test/java/com/faster/product/app/product/application/usecase/ProductServiceTest.java
  product/src/test/product.http
Labels: ✨ feature

#170 [order] 주문 서비스 명세에 따른 이넘값 수정 외
  order/src/main/java/com/faster/order/app/order/domain/criteria/SearchOrderCriteria.java
  order/src/main/java/com/faster/order/app/order/domain/enums/OrderStatus.java
  order/src/main/java/com/faster/order/app/order/infrastructure/persistence/jpa/OrderJpaRepositoryCustomImpl.java
  order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
  order/src/main/java/com/faster/order/app/order/presentation/dto/request/InternalUpdateOrderStatusRequestDto.java
Labels: ♻️ refactor

#174 [company] search
  company/src/main/java/com/faster/company/app/company/application/dto/request/GetCompaniesApplicationRequestDto.java
  company/src/main/java/com/faster/company/app/company/application/dto/request/SearchCompaniesCondition.java
  company/src/main/java/com/faster/company/app/company/application/dto/response/GetCompaniesApplicationResponseDto.java
  company/src/main/java/com/faster/company/app/company/application/usecase/CompanyService.java
  company/src/main/java/com/faster/company/app/company/application/usecase/CompanyServiceImpl.java
  company/src/main/java/com/faster/company/app/company/domain/projection/SearchCompaniesProjection.java
  company/src/main/java/com/faster/company/app/company/domain/repository/CompanyRepository.java
  company/src/main/java/com/faster/company/app/company/infrastructure/persistence/command/SearchCompaniesByConditionCommand.java
  company/src/main/java/com/faster/company/app/company/infrastructure/persistence/jpa/CompanyJpaRepository.java
  company/src/main/java/com/faster/company/app/company/infrastructure/persistence/jpa/CompanyJpaRepositoryCustom.java
  company/src/main/java/com/faster/company/app/company/infrastructure/persistence/jpa/CompanyJpaRepositoryCustomImpl.java
  company/src/main/java/com/faster/company/app/company/infrastructure/persistence/util/QuerydslUtil.java
  company/src/main/java/com/faster/company/app/company/presentation/CompanyController.java
  company/src/main/java/com/faster/company/app/company/presentation/dto/response/GetCompaniesResponseDto.java
  company/src/main/java/com/faster/company/app/global/config/QuerydslConfig.java
  company/src/main/java/com/faster/company/app/global/exception/CompanyErrorCode.java
  company/src/test/company.http
Labels: ✨ feature

#177 [hub] 허브담당자의 허브 조회
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubService.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
  hub/src/main/java/com/faster/hub/app/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubInternalController.java
  hub/src/test/hub.http
Labels: ✨ feature

#180 [delivery] 배송 목록 조회 기능 구현 외
  delivery/src/main/java/com/faster/delivery/app/delivery/application/CompanyClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/DeliveryManagerClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/HubClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/DeliveryGetElementDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/HubDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryService.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/strategy/SearchByCompany.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/strategy/SearchByDelivery.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/strategy/SearchByHub.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/strategy/SearchByMaster.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/strategy/SearchByRole.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/criteria/DeliveryCriteria.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/CompanyClientImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/CompanyFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/DeliveryManagerClientImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/DeliveryManagerFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/HubClientImplForDelivery.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/HubFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/hub/HubGetListResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/jpa/DeliveryRepositoryCustom.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/jpa/DeliveryRepositoryCustomImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryApiController.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerService.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/repository/DeliveryManagerRepository.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/HubClientImplForDeliveryManager.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/HubFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/jpa/DeliveryManagerJpaRepository.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/DeliveryManagerInternalController.java
  delivery/src/main/java/com/faster/delivery/app/global/common/QueryDslUtil.java
  delivery/src/main/java/com/faster/delivery/app/global/config/FeignClientConfig.java
  delivery/src/main/resources/application-develop.yml
  delivery/src/main/resources/application.yml
Labels: ✨ feature

#183 [product] 상품 리팩토링
  product/src/main/java/com/faster/product/app/global/config/FeignClientConfig.java
  product/src/main/java/com/faster/product/app/global/exception/ProductErrorCode.java
  product/src/main/java/com/faster/product/app/global/feign/FeignClientErrorDecoder.java
  product/src/main/java/com/faster/product/app/product/application/dto/response/GetCompanyApplicationResponseDto.java
  product/src/main/java/com/faster/product/app/product/domain/criteria/SearchProductCriteria.java
  product/src/main/java/com/faster/product/app/product/infrastructure/feign/dto/response/GetCompanyResponseDto.java
  product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepositoryCustomImpl.java
  product/src/main/java/com/faster/product/app/product/presentation/ProductController.java
  product/src/main/java/com/faster/product/app/product/presentation/ProductInternalController.java
  product/src/test/product.http
Labels: ♻️ refactor

#182 [delivery] 생성 시 업체 배송담당자 배정 및 메시지 전송
  delivery/src/main/java/com/faster/delivery/app/delivery/application/DeliveryManagerClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/MessageClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/DeliveryManagerDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/DeliverySaveApplicationDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/DeliverySaveDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/HubRouteDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/SendMessageApplicationRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryService.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/strategy/SearchByDelivery.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/CompanyClientImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/CompanyFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/DeliveryManagerClientImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/DeliveryManagerFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/MessageClientImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/MessageFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/SendMessageFeignRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/deliverymanager/DeliveryManagerGetResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/hub/HubPathResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryApiController.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryInternalController.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/api/DeliverySaveRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/internal/DeliverySaveInternalRequestDto.java
Labels: ✨ feature

#186 [delivery] 배송 상태 업데이트 기능 보완
  delivery/src/main/java/com/faster/delivery/app/delivery/application/OrderClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/OrderUpdateApplicationRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/OrderUpdateApplicationResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/OrderClientImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/OrderFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/order/OrderUpdateRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/order/OrderUpdateResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/internal/OrderUpdateResponseDto.java
Labels: ✨ feature

#188 [delivery] 배송 경로 배송담장자 유저 id 컬럼 추가
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/DeliveryRoute.java
Labels: ✨ feature

#189 [order] 주문 리팩토링
  order/build.gradle
  order/src/main/java/com/faster/order/app/global/config/FeignClientConfig.java
  order/src/main/java/com/faster/order/app/global/filter/LoggingFilter.java
  order/src/main/java/com/faster/order/app/order/application/dto/request/UpdateStocksApplicationRequestDto.java
  order/src/main/java/com/faster/order/app/order/domain/entity/Order.java
  order/src/main/java/com/faster/order/app/order/domain/entity/OrderItem.java
  order/src/main/java/com/faster/order/app/order/domain/entity/OrderItems.java
  order/src/main/java/com/faster/order/app/order/domain/entity/OrdererInfo.java
  order/src/main/resources/application.yml
  order/src/main/resources/logback-spring.xml
  order/src/main/resources/logback/error-file-appender.xml
  order/src/main/resources/logback/info-file-appender.xml
  order/src/main/resources/properties/zipkin.yml
Labels: ♻️ refactor

#179 [message] internal 구현하기
  message/src/main/java/com/faster/message/MessageApplication.java
  message/src/main/java/com/faster/message/app/message/application/client/HubClient.java
  message/src/main/java/com/faster/message/app/message/application/client/OrderClient.java
  message/src/main/java/com/faster/message/app/message/application/client/UserClient.java
  message/src/main/java/com/faster/message/app/message/application/dto/SaveGeminiMessageRequestDto.java
  message/src/main/java/com/faster/message/app/message/application/dto/SaveMessageRequestDto.java
  message/src/main/java/com/faster/message/app/message/application/dto/request/ASaveMessageRequestDto.java
  message/src/main/java/com/faster/message/app/message/application/dto/response/AGetDeliveryManagerResponseDto.java
  message/src/main/java/com/faster/message/app/message/application/dto/response/AGetDeliveryResponseDto.java
  message/src/main/java/com/faster/message/app/message/application/dto/response/AGetHubResponseDto.java
  message/src/main/java/com/faster/message/app/message/application/dto/response/AGetOrderResponseDto.java
  message/src/main/java/com/faster/message/app/message/application/dto/response/AGetUserResponseDto.java
  message/src/main/java/com/faster/message/app/message/application/dto/response/ASaveMessageResponseDto.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageService.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageServiceImpl.java
  message/src/main/java/com/faster/message/app/message/domain/entity/Message.java
  message/src/main/java/com/faster/message/app/message/domain/repository/MessageRepository.java
  message/src/main/java/com/faster/message/app/message/infrastructure/HubClientImpl.java
  message/src/main/java/com/faster/message/app/message/infrastructure/OrderClientImpl.java
  message/src/main/java/com/faster/message/app/message/infrastructure/UserClientImpl.java
  message/src/main/java/com/faster/message/app/message/infrastructure/fegin/HubFeignClient.java
  message/src/main/java/com/faster/message/app/message/infrastructure/fegin/OrderFeignClient.java
  message/src/main/java/com/faster/message/app/message/infrastructure/fegin/UserFeignClient.java
  message/src/main/java/com/faster/message/app/message/infrastructure/fegin/dto/response/IGetHubResponseDto.java
  message/src/main/java/com/faster/message/app/message/infrastructure/fegin/dto/response/IGetOrderResponseDto.java
  message/src/main/java/com/faster/message/app/message/infrastructure/fegin/dto/response/IGetUserResponseDto.java
  message/src/main/java/com/faster/message/app/message/infrastructure/persistence/jpa/MessageJpaRepository.java
  message/src/main/java/com/faster/message/app/message/presentation/MessageInternalController.java
  message/src/main/java/com/faster/message/app/message/presentation/dto/request/PSaveMessageRequestDto.java
  message/src/main/java/com/faster/message/app/message/presentation/dto/response/PSaveMessageResponseDto.java
  message/src/main/java/com/faster/message/app/message/presentation/dto/response/SaveMessageResponseDto.java
  message/src/main/java/com/faster/message/app/message/presentation/internal/MessageInternalController.java
  message/src/main/resources/application.yml
Labels: ✨ feature

#193 [user]회원 리팩토링
  user/src/main/java/com/faster/user/app/global/exception/enums/UserErrorCode.java
  user/src/main/java/com/faster/user/app/user/application/dto/response/AGetUserResponseDto.java
  user/src/main/java/com/faster/user/app/user/facade/UserFacade.java
  user/src/main/java/com/faster/user/app/user/facade/UserFacadeImpl.java
  user/src/main/java/com/faster/user/app/user/presentation/InternalUserController.java
  user/src/main/java/com/faster/user/app/user/presentation/UserController.java
  user/src/main/java/com/faster/user/app/user/presentation/dto/response/PGetUserResponseDto.java
Labels: ✨ feature

#196 [message] 생성된 메시지 슬랙 발송 구현
  message/src/main/java/com/faster/message/app/global/enums/MessageErrorCode.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageServiceImpl.java
  message/src/main/java/com/faster/message/app/message/presentation/MessageInternalController.java
  message/src/main/resources/application.yml
Labels: ✨ feature

#197 [company] 업체 리팩토링
  company/build.gradle
  company/src/main/java/com/faster/company/app/company/application/usecase/CompanyServiceImpl.java
  company/src/main/java/com/faster/company/app/company/infrastructure/feign/ProductFeignClient.java
  company/src/main/java/com/faster/company/app/company/presentation/CompanyInternalController.java
  company/src/main/java/com/faster/company/app/global/config/FeignClientConfig.java
  company/src/main/java/com/faster/company/app/global/feign/FeignClientErrorDecoder.java
  company/src/main/java/com/faster/company/app/global/filter/LoggingFilter.java
  company/src/main/resources/application.yml
  company/src/main/resources/db/data.sql
  company/src/main/resources/logback-spring.xml
  company/src/main/resources/logback/error-file-appender.xml
  company/src/main/resources/logback/info-file-appender.xml
  company/src/main/resources/properties/zipkin.yml
  company/src/test/company.http
Labels: ♻️ refactor

#199 [product] 상품 리팩토링
  product/build.gradle
  product/src/main/java/com/faster/product/app/global/exception/ProductErrorCode.java
  product/src/main/java/com/faster/product/app/global/filter/LoggingFilter.java
  product/src/main/java/com/faster/product/app/product/application/client/CompanyClient.java
  product/src/main/java/com/faster/product/app/product/application/client/HubClient.java
  product/src/main/java/com/faster/product/app/product/application/dto/response/GetCompanyApplicationResponseDto.java
  product/src/main/java/com/faster/product/app/product/application/dto/response/GetHubsApplicationResponseDto.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/infrastructure/CompanyClientImpl.java
  product/src/main/java/com/faster/product/app/product/infrastructure/HubClientImpl.java
  product/src/main/java/com/faster/product/app/product/infrastructure/feign/HubFeignClient.java
  product/src/main/java/com/faster/product/app/product/infrastructure/feign/dto/response/GetCompanyResponseDto.java
  product/src/main/java/com/faster/product/app/product/infrastructure/feign/dto/response/GetHubsResponseDto.java
  product/src/main/resources/application.yml
  product/src/main/resources/logback-spring.xml
  product/src/main/resources/logback/error-file-appender.xml
  product/src/main/resources/logback/info-file-appender.xml
  product/src/main/resources/properties/zipkin.yml
  product/src/test/product.http
Labels: ♻️ refactor

#203 [#202][deliveryManager] feat: 배송 담당자 목록 조회 기능 추가
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/HubClientImplForDelivery.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/HubFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/hub/HubPathRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/dto/DeliveryManagerElementDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerService.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/strategy/SearchByDeliveryForDeliveryManager.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/strategy/SearchByHubForDeliveryManager.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/strategy/SearchByMasterForDeliveryManager.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/strategy/SearchByRoleForDeliveryManager.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/criteria/DeliveryManagerCriteria.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/repository/DeliveryManagerRepository.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/jpa/DeliveryManagerRepositoryCustom.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/jpa/DeliveryManagerRepositoryCustomImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/DeliveryManagerApiController.java
Labels: ✨ feature

#205 [message] 메시지 리팩토링
  message/src/main/java/com/faster/message/app/message/application/dto/request/ASaveMessageRequestDto.java
  message/src/main/java/com/faster/message/app/message/application/dto/response/AGetOrderResponseDto.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageServiceImpl.java
  message/src/main/java/com/faster/message/app/message/infrastructure/fegin/dto/response/IGetHubResponseDto.java
  message/src/main/java/com/faster/message/app/message/infrastructure/fegin/dto/response/IGetOrderResponseDto.java
  message/src/main/java/com/faster/message/app/message/presentation/MessageInternalController.java
  message/src/main/java/com/faster/message/app/message/presentation/dto/request/PSaveMessageRequestDto.java
Labels: ♻️ refactor

#207 [delivery] 허브 배송 담당자 배정
  delivery/src/main/java/com/faster/delivery/app/delivery/application/DeliveryManagerClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/DeliveryScheduler.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/AssignDeliveryManagerApplicationResponse.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/AssignedDeliveryRouteDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/SendMessageApplicationRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryService.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/repository/DeliveryRepository.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/DeliveryManagerClientImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/DeliveryManagerFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/deliverymanager/AssignDeliveryManagerFeignRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/deliverymanager/AssignDeliveryManagerFeignResponse.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/type/DeliveryManagerType.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/jpa/DeliveryRepositoryCustom.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/jpa/DeliveryRepositoryCustomImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryInternalController.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/dto/AssignDeliveryManagerApplicationRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/dto/AssignDeliveryManagerApplicationResponse.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/dto/AssignedHubDeliveryManagerDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/type/DeliveryManagerType.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerService.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/repository/DeliveryManagerRepository.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/jpa/DeliveryManagerJpaRepository.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/redis/CompanyManagerSequenceRepository.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/redis/ManagerSequenceRepository.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/redis/ManagerSequenceRepositoryImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/DeliveryManagerInternalController.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/dto/AssignDeliveryManagerRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/dto/internal/AssignDeliveryManagerResponse.java
  delivery/src/main/java/com/faster/delivery/app/global/config/EnableSchedulingConfig.java
  delivery/src/test/delivery-manager.http
Labels: ✨ feature

#209 [hub] route 캐싱 작업
  hub/build.gradle
  hub/src/main/java/com/faster/hub/app/global/config/RedisCacheConfig.java
  hub/src/main/java/com/faster/hub/app/global/config/RedisConfig.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
  hub/src/main/resources/application.yml
  hub/src/main/resources/properties/redis.yml
Labels: ✨ feature

#213 [hub] 허브 캐싱 처리 및 data.sql 추가
  hub/src/main/java/com/faster/hub/app/global/config/RedisCacheConfig.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
  hub/src/main/resources/db/data.sql
  hub/src/main/resources/properties/datasource.yml
  hub/src/main/resources/properties/jpa.yml
  hub/src/test/hub.http
Labels: ✨ feature

#212 [delivery, deliveryManager] 배송매니저 sequence 동시성문제 해결
  delivery/build.gradle
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/DeliveryRoute.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/facade/DeliveryManagerFacade.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/facade/DeliveryManagerFacadeImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerService.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/entity/DeliveryManager.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/repository/DeliveryManagerRepository.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/jpa/DeliveryManagerJpaRepository.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/jpa/DeliveryManagerRepositoryCustomImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/DeliveryManagerApiController.java
  delivery/src/main/resources/application-develop.yml
  delivery/src/main/resources/db/data.sql
Labels: ✨ feature

#215 [hub] redis config password
  hub/src/main/java/com/faster/hub/app/global/config/RedisCacheConfig.java
  hub/src/main/java/com/faster/hub/app/global/config/RedisConfig.java
  hub/src/main/java/com/faster/hub/app/hub/application/usecase/HubServiceImpl.java
  hub/src/main/resources/properties/redis.yml
Labels: ✨ feature

#219 [hub] 추가/수정 시, 소속 허브 ID가 존재하는 허브인지 확인
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/dto/DeliveryManagerUpdateDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/entity/DeliveryManager.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/dto/api/DeliveryManagerUpdateRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/global/exception/DeliveryManagerErrorCode.java
Labels: ✨ feature

#222 [#221][deliveryManager] 테스트에 의한 수정사항 반영
  company/src/main/java/com/faster/company/app/company/presentation/dto/response/IGetCompanyResponseDto.java
  company/src/main/resources/properties/datasource.yml
  company/src/main/resources/properties/jpa.yml
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/DeliveryDetailDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/DeliveryUpdateDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/faster/delivery/app/delivery/domain/entity/DeliveryRoute.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/DeliveryManagerFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/HubFeignClient.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/deliverymanager/DeliveryManagerGetResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/api/DeliveryGetDetailResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/api/DeliveryUpdateRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/dto/internal/DeliveryUpdateInternalRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/dto/DeliveryManagerDetailDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/repository/DeliveryManagerRepository.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/client/UserFeginClient.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/jpa/DeliveryManagerJpaRepository.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/jpa/DeliveryManagerRepositoryCustomImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/DeliveryManagerInternalController.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/dto/internal/DeliveryManagerGetDetailResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/global/config/RedisConfig.java
  delivery/src/main/resources/application-develop.yml
  delivery/src/main/resources/db/data.sql
  delivery/src/test/delivery-manager.http
  delivery/src/test/delivery.http
  message/src/main/resources/application.yml
  server/src/main/resources/application.yml
Labels: ✨ feature

#218 [order] 주문 리팩토링
  .gitignore
  order/src/main/java/com/faster/order/app/order/application/dto/response/GetCompanyApplicationResponseDto.java
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
  order/src/main/java/com/faster/order/app/order/infrastructure/feign/dto/response/GetCompanyResponseDto.java
  order/src/main/resources/db/data.sql
  order/src/test/order.http
Labels: ♻️ refactor

#225 [develop, developManager] 2차 테스트 수정분 반영, zipkin 추가
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/CompanyDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/strategy/SearchByCompany.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/company/CompanyGetResponseDto.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
  delivery/src/main/resources/application-develop.yml
  delivery/src/test/delivery-manager.http
  delivery/src/test/delivery.http
  order/build.gradle
Labels: ♻️ refactor, ✨ feature

#227 [user, message, delivery] 주문 openfeign 조회 실패 리팩토링
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  message/src/main/java/com/faster/message/app/global/feign/FeignClientConfig.java
  message/src/main/java/com/faster/message/app/global/feign/FeignClientErrorDecoder.java
  message/src/main/java/com/faster/message/app/global/filter/LoggingFilter.java
  message/src/main/java/com/faster/message/app/message/application/dto/response/ASaveMessageResponseDto.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageServiceImpl.java
  message/src/main/java/com/faster/message/app/message/infrastructure/fegin/OrderFeignClient.java
  message/src/main/java/com/faster/message/app/message/presentation/MessageInternalController.java
  message/src/main/resources/application.yml
  user/src/main/java/com/faster/user/app/auth/config/RedisConfig.java
Labels: ♻️ refactor, ✨ feature

#232 [dlievery, message, user] openfeign 연동 코드 수정
  delivery/src/main/java/com/faster/delivery/app/delivery/application/dto/SendMessageApplicationRequestDto.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/client/dto/SendMessageFeignRequestDto.java
  delivery/src/test/delivery.http
  message/src/main/java/com/faster/message/app/message/application/dto/request/ASaveMessageRequestDto.java
  message/src/main/java/com/faster/message/app/message/application/usecase/MessageServiceImpl.java
  message/src/main/java/com/faster/message/app/message/presentation/MessageInternalController.java
  message/src/main/java/com/faster/message/app/message/presentation/dto/request/PSaveMessageRequestDto.java
  user/src/main/resources/application.yml
  user/src/main/resources/properties/jpa.yml
  user/src/main/resources/properties/redis.yml
Labels: ♻️ refactor

#230 [hub] zipkin, logback, filter 리펙토링
  hub/build.gradle
  hub/src/main/java/com/faster/hub/app/global/filter/LoggingFilter.java
  hub/src/main/resources/application.yml
  hub/src/main/resources/logback-spring.xml
  hub/src/main/resources/logback/error-file-appender.xml
  hub/src/main/resources/logback/info-file-appender.xml
  hub/src/main/resources/properties/base.yml
  hub/src/main/resources/properties/cloud.yml
  hub/src/main/resources/properties/datasource.yml
  hub/src/main/resources/properties/zipkin.yml
Labels: ✨ feature

#235 [order, product] 오류 보완
  order/src/main/java/com/faster/order/app/order/application/usecase/OrderServiceImpl.java
  product/src/test/java/com/faster/product/app/product/application/usecase/ProductServiceTest.java
Labels: ♻️ refactor

#239 [common] 데이터 생성 프로시저 추가
  procedure/procedure hub_manager.sql
  procedure/procedure_company_product.sql
  procedure/procedure_delivery.sql
  procedure/procedure_delivery_manager.sql
  procedure/procedure_one.sql
  procedure/procedure_order.sql
Labels: ✨ feature

#246 [common] swagger 설정
  company/build.gradle
  company/src/main/java/com/faster/company/app/company/presentation/CompanyController.java
  company/src/main/java/com/faster/company/app/company/presentation/CompanyInternalController.java
  company/src/main/java/com/faster/company/app/global/config/SwaggerConfig.java
  delivery/build.gradle
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryApiController.java
  delivery/src/main/java/com/faster/delivery/app/delivery/presentaion/DeliveryInternalController.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/DeliveryManagerApiController.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/presentation/DeliveryManagerInternalController.java
  delivery/src/main/java/com/faster/delivery/app/global/common/SwaggerConfig.java
  hub/build.gradle
  hub/src/main/java/com/faster/hub/app/global/config/SwaggerConfig.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubController.java
  hub/src/main/java/com/faster/hub/app/hub/presentation/HubInternalController.java
  message/build.gradle
  message/src/main/java/com/faster/message/app/global/config/SwaggerConfig.java
  message/src/main/java/com/faster/message/app/message/presentation/MessageInternalController.java
  order/build.gradle
  order/src/main/java/com/faster/order/app/global/config/SwaggerConfig.java
  order/src/main/java/com/faster/order/app/order/presentation/OrderController.java
  order/src/main/java/com/faster/order/app/order/presentation/OrderInternalController.java
  product/build.gradle
  product/src/main/java/com/faster/product/app/global/config/SwaggerConfig.java
  product/src/main/java/com/faster/product/app/product/presentation/ProductController.java
  product/src/main/java/com/faster/product/app/product/presentation/ProductInternalController.java
  user/build.gradle
  user/src/main/java/com/faster/user/app/auth/config/SecurityConfig.java
  user/src/main/java/com/faster/user/app/auth/presentation/controller/AuthController.java
  user/src/main/java/com/faster/user/app/global/config/SwaggerConfig.java
  user/src/main/java/com/faster/user/app/user/presentation/InternalUserController.java
  user/src/main/java/com/faster/user/app/user/presentation/UserController.java
Labels: ✨ feature

#242 [hub] feat: 외부 api 재시도 적용
  hub/build.gradle
  hub/src/main/java/com/faster/hub/app/global/exception/NaverDirectionApiErrorCode.java
  hub/src/main/java/com/faster/hub/app/hub/infrastructure/client/NaverDirectionsApiClientImpl.java
  hub/src/main/resources/application.yml
  hub/src/main/resources/properties/resilience4j-retry.yml
Labels: ♻️ refactor, ✨ feature

#243 [#241][all] feat: 로그백 추가
  .gitignore
  delivery/src/main/resources/logback-spring.xml
  delivery/src/main/resources/logback/error-file-appender.xml
  delivery/src/main/resources/logback/info-file-appender.xml
  gateway/src/main/resources/logback-spring.xml
  gateway/src/main/resources/logback/error-file-appender.xml
  gateway/src/main/resources/logback/info-file-appender.xml
  message/src/main/resources/logback-spring.xml
  message/src/main/resources/logback/error-file-appender.xml
  message/src/main/resources/logback/info-file-appender.xml
  server/src/main/resources/logback-spring.xml
  server/src/main/resources/logback/error-file-appender.xml
  server/src/main/resources/logback/info-file-appender.xml
  user/src/main/resources/logback-spring.xml
  user/src/main/resources/logback/error-file-appender.xml
  user/src/main/resources/logback/info-file-appender.xml
Labels: ✨ feature

#256 [order, company, product] 컬럼 길이 수정 및 로직 보완
  .gitignore
  company/src/main/java/com/faster/company/app/company/domain/entity/Company.java
  order/src/main/java/com/faster/order/app/order/domain/entity/OrderItem.java
  product/src/main/java/com/faster/product/app/product/application/usecase/ProductServiceImpl.java
  product/src/main/java/com/faster/product/app/product/domain/entity/Product.java
  product/src/main/java/com/faster/product/app/product/infrastructure/persistence/jpa/ProductJpaRepositoryCustomImpl.java
Labels: ♻️ refactor

#254 [hub, delivery] 리펙토링
  delivery/src/main/java/com/faster/delivery/app/delivery/application/DeliveryScheduler.java
  delivery/src/main/java/com/faster/delivery/app/delivery/application/usecase/DeliveryServiceImpl.java
  hub/src/main/resources/application.yml
  hub/src/main/resources/properties/base.yml
  hub/src/main/resources/properties/cloud.yml
  hub/src/main/resources/properties/datasource.yml
  hub/src/main/resources/properties/jpa.yml
  hub/src/main/resources/properties/zipkin.yml
Labels: ✨ feature

#259 [delivery] 허브 배송 담당자 로직 수정
  delivery/src/main/java/com/faster/delivery/app/delivery/infrastructure/jpa/DeliveryRepositoryCustomImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/application/usecase/DeliveryManagerServiceImpl.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/domain/repository/DeliveryManagerRepository.java
  delivery/src/main/java/com/faster/delivery/app/deliverymanager/infrastructure/jpa/DeliveryManagerJpaRepository.java
Labels: 🐛 bug
